### ISSUE TITLE
Are pull requests welcome?

### ISSUE THREAD

**Issue by kevboh** [amandavisconti/infinite-ulysses-public#141]
I'm interested in:
1. Helping you, because this idea is great.
2. Running the site locally to test changes.
3. Submitting those changes.

Is that a good idea? If so, how would I go about running locally?

(Congrats on defending your dissertation.)

**Comment by amandavisconti** [comment]
Yes! I'm sorry I didn't notice this issue until now—my notifications must not be turned on. Thank you for your interest! I'm at the CODEX Hackathon right now working on getting the site to be something you can easily run locally/turn into your own site/make pull requests for.

**Comment by kevboh** [comment]
Sounds great. I'll keep an eye out. Thanks.
