### ISSUE TITLE
Beta Ribbon causes horizontal scroll

### ISSUE THREAD

**Issue by jessemenn** [amandavisconti/infinite-ulysses-public#44]
Also unsure why it's in an anchor tag to research statement. 
Adding the following to ribbon-wrapper div fixes it: "overflow: hidden; height: 100%" (at least on Yosemite, Chrome Version 41.0.2272.76 (64-bit).

**Comment by amandavisconti** [comment]
Thanks! I may also finish by adjusting the image file itself (the problem is that CSS rotating the ribbon makes a corner stick out to the right).

**Comment by amandavisconti** [comment]
Fix to horizontal scroll created full-height <a> that is behind sidebar's z-index. Sometimes people accidentally click here and get taken to the research page.

**Comment by amandavisconti** [comment]
Solved by beta ribbon removal for 1.0 site theming (currently local)
