### ISSUE TITLE
Add Lacuna Stories logo to front page

### ISSUE THREAD

**Issue by amandavisconti** [amandavisconti/infinite-ulysses-public#86]

**Comment by mwidner** [comment]
![lacunastories](https://cloud.githubusercontent.com/assets/1418401/8027247/098c75d0-0d49-11e5-8e37-a6e1c79d42e3.jpg) This may help. :)

**Comment by amandavisconti** [comment]
Thanks! Adding this for the upcoming site design upgrade.
